-- DELETE TABLES
DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS Todos;

--CREATE TABLES
CREATE TABLE Users (
  id SERIAL PRIMARY KEY,
  username VARCHAR(30) NOT NULL UNIQUE,
  password_hash VARCHAR(520) NOT NULL
);

CREATE TABLE Todos (
  id SERIAL PRIMARY KEY,
  description VARCHAR(200) NOT NULL,
  done BOOLEAN NOT NULL,
  created_at TIMESTAMP NOT NULL,
  user_id INT NOT NULL,
  CONSTRAINT fk_user
      FOREIGN KEY(user_id)
	  REFERENCES Users(id)
	  ON DELETE CASCADE
);
